# Generated by Django 4.1.7 on 2023-02-26 16:59

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='Category',
            field=models.CharField(choices=[('Set', 'Набор'), ('Collection', 'Коллекционные'), ('Series', 'Серия')], default='null', max_length=16, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='articles',
            name='Category_full',
            field=models.CharField(blank=True, max_length=50, verbose_name='Описание категории'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги'),
        ),
    ]
