# Generated by Django 4.1.7 on 2023-02-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_articles_category_articles_category_full_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='Category',
            field=models.CharField(choices=[('Set', 'Набор'), ('Collection', 'Коллекционные'), ('Series', 'Серия')], default='unknown', max_length=16, verbose_name='Категория'),
        ),
    ]
