# Generated by Django 4.1.7 on 2023-02-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_articles_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='Category_full',
        ),
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.CharField(choices=[('Null', ' --------- '), ('Set', 'Набор'), ('Collection', 'Коллекционные'), ('Series', 'Серия')], default='Null', max_length=16, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='articles',
            name='category_full',
            field=models.CharField(blank=True, max_length=50, verbose_name='Описание категории'),
        ),
    ]
