# Generated by Django 4.1.7 on 2023-03-01 14:08

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('main', '0004_remove_articles_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='cover',
            field=models.ImageField(upload_to='images/', verbose_name='Основное фото'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Введите теги через запятую или выберите из уже существующих', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги'),
        ),
    ]
