# Generated by Django 4.0.5 on 2023-03-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_articles_category_alter_articles_tags_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='tag_field',
            field=models.CharField(choices=[('Миньоны', 'Миньоны'), ('НеМиньоны', 'НеМиньоны'), ('КтоТо', 'КтоТо'), ('FSPшники', 'FSPшники')], default=0, max_length=100),
            preserve_default=False,
        ),
    ]
