# Generated by Django 4.0.5 on 2023-03-03 17:16

from django.db import migrations, models
import multiselectfield.db.fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('main', '0008_alter_articles_tag_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'изображение', 'verbose_name_plural': 'Дополнительные изображения'},
        ),
        migrations.AlterField(
            model_name='articles',
            name='tag_field',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('миньоны', 'Миньоны'), ('неминьоны', 'НеМиньоны'), ('ктото', 'КтоТо'), ('fspшники', 'FSPшники'), ('гдето', 'ГдеТо'), ('комуто', 'КомуТо')], max_length=45, verbose_name='Существующие Теги'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Введите теги через запятую с большой буквы, без пробелов', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Новые теги'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Изображения:'),
        ),
    ]
