# Generated by Django 4.0.5 on 2023-03-07 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_image_options_alter_articles_tag_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='tag_field',
        ),
    ]
