# Generated by Django 4.1.7 on 2023-03-07 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_articles_tag_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='tag_field',
        ),
    ]
