# Generated by Django 4.0.5 on 2023-03-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_image_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='article',
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
