# Generated by Django 4.0.5 on 2023-03-12 14:32

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='TovarCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='main/static/main/img', verbose_name='Основное фото')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('category', models.CharField(choices=[('Null', '---------'), ('Set', 'Набор'), ('Collection', 'Коллекционные'), ('Series', 'Серия')], default='Null', max_length=16, verbose_name='Категория')),
                ('category_full', models.CharField(blank=True, max_length=50, verbose_name='Описание категории')),
                ('full_text', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='TovarTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='Введите теги через запятую с большой буквы, без пробелов', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Новые теги')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
    ]
