# Generated by Django 4.0.5 on 2023-03-12 14:44

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('tovar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='main/static/main/img', verbose_name='Изображения:')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Дополнительные изображения',
            },
        ),
        migrations.AddField(
            model_name='tovarcreate',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Введите теги через запятую с большой буквы, без пробелов', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Новые теги'),
        ),
        migrations.DeleteModel(
            name='TovarTags',
        ),
        migrations.AddField(
            model_name='image',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tovar.tovarcreate'),
        ),
    ]
