# Generated by Django 4.1.7 on 2023-06-11 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tovar', '0002_image_tovarcreate_tags_delete_tovartags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Карусель',
                'verbose_name_plural': 'Карусели',
            },
        ),
        migrations.AlterField(
            model_name='tovarcreate',
            name='category',
            field=models.CharField(choices=[('Ordinary', 'Обычные'), ('Collection', 'Коллекционные'), ('Popular', 'Популярные')], default='Null', max_length=16, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='tovarcreate',
            name='category_full',
            field=models.CharField(blank=True, max_length=250, verbose_name='Описание категории'),
        ),
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='main/static/main/img', verbose_name='Изображение')),
                ('carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tovar.carousel')),
            ],
            options={
                'verbose_name': 'Изображение карусели',
                'verbose_name_plural': 'Изображения карусели',
            },
        ),
    ]
