# Generated by Django 4.1.7 on 2023-06-11 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tovar', '0003_carousel_alter_tovarcreate_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'Карусель', 'verbose_name_plural': 'Карусель'},
        ),
    ]
