# Generated by Django 4.1.7 on 2023-06-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tovar', '0004_alter_carousel_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tovarcreate',
            old_name='full_text',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='tovarcreate',
            name='category_full',
        ),
        migrations.AddField(
            model_name='tovarcreate',
            name='short_description',
            field=models.CharField(blank=True, max_length=250, verbose_name='Краткое описание'),
        ),
    ]
