# Generated by Django 4.1.7 on 2023-06-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tovar', '0005_rename_full_text_tovarcreate_description_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tovarcreate',
            index=models.Index(fields=['title'], name='tovar_tovar_title_57ecf7_idx'),
        ),
    ]
