# Generated by Django 4.1.7 on 2023-06-11 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tovar', '0006_tovarcreate_tovar_tovar_title_57ecf7_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tovarcreate',
            name='tovar_tovar_title_57ecf7_idx',
        ),
    ]
