# Generated by Django 4.1.7 on 2023-06-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tovar', '0007_remove_tovarcreate_tovar_tovar_title_57ecf7_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Использовать'),
        ),
    ]
