# Generated by Django 4.1.7 on 2023-07-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tovar', '0008_carousel_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='is_used',
        ),
    ]
