# Generated by Django 4.1.7 on 2023-07-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tovar', '0009_remove_carousel_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselimage',
            name='image',
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='carousel',
            field=models.ImageField(upload_to='main/static/main/img', verbose_name='Фото'),
        ),
    ]
