# Generated by Django 4.1.7 on 2023-07-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tovar', '0010_remove_carouselimage_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarouselImage',
        ),
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'Изображение карусели', 'verbose_name_plural': 'Изображения карусели'},
        ),
        migrations.AddField(
            model_name='carousel',
            name='photo',
            field=models.ImageField(default=1, upload_to='main/static/main/img', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
