# Generated by Django 4.1.7 on 2023-07-06 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tovar', '0009_maincarousel'),
        ('tovar', '0011_delete_carouselimage_alter_carousel_options_and_more'),
    ]

    operations = [
    ]
