# Generated by Django 4.1.7 on 2023-07-06 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tovar', '0012_merge_20230706_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainCarousel',
        ),
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'Изображение для карусели', 'verbose_name_plural': 'Изображения для карусели'},
        ),
    ]
